services:
  stats-server:
    build: ./ewm-stats-service/stats-service-app
    ports:
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/statsdb
      SPRING_DATASOURCE_USERNAME: statsuser
      SPRING_DATASOURCE_PASSWORD: statspass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      stats-db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app-network

  stats-db:
    image: postgres:16.1
    environment:
      POSTGRES_DB: statsdb
      POSTGRES_USER: statsuser
      POSTGRES_PASSWORD: statspass
    ports:
      - "5433:5432"
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
    #volumes:
     # - postgres_data_stats:/var/lib/postgresql/data
    networks:
      - app-network

  ewm-service:
    build: ./ewm-main-service/main-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ewm-db:5432/ewmdb
      SPRING_DATASOURCE_USERNAME: ewmuser
      SPRING_DATASOURCE_PASSWORD: ewmpass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      ewm-db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app-network

  ewm-db:
    image: postgres:16.1
    environment:
      POSTGRES_DB: ewmdb
      POSTGRES_USER: ewmuser
      POSTGRES_PASSWORD: ewmpass
    ports:
      - "5431:5432"
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
    #volumes:
     # - postgres_data_main:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

#volumes:
 # postgres_data_stats:
  #postgres_data_main:
