server.port=9090

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/statsdb
spring.datasource.username=statsuser
spring.datasource.password=statspass

# Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
